# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'NFC Access Control System'
copyright = '2025, RWU NFC Lab'
author = 'RWU NFC Lab'
release = '1.0.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.graphviz',
    'sphinxcontrib.plantuml',
]

templates_path = ['_templates']
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

# -- Options for Breathe extension -------------------------------------------
# Breathe is used for C++ API documentation from Doxygen XML output

breathe_projects = {
    "NFC Access Control": "../doxygen/xml"
}
breathe_default_project = "NFC Access Control"

# -- Options for Graphviz extension ------------------------------------------

graphviz_output_format = 'svg'

# -- Options for PlantUML extension ------------------------------------------

# PlantUML configuration
# First check if local plantuml.jar exists, otherwise use online server
import os
plantuml_jar_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'plantuml.jar')

if os.path.exists(plantuml_jar_path):
    # Use local PlantUML jar (run docs/setup_plantuml.ps1 to download)
    plantuml = f'java -jar "{plantuml_jar_path}"'
else:
    # Fallback to online PlantUML server
    plantuml = 'https://www.plantuml.com/plantuml'

plantuml_output_format = 'svg'
plantuml_latex_output_format = 'pdf'

# -- Options for todo extension ----------------------------------------------

todo_include_todos = True

# -- Additional options ------------------------------------------------------

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output -------------------------------------------------

html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['custom.css']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# -- Options for LaTeX output ------------------------------------------------

# LaTeX configuration with Unicode support using standard fonts
latex_engine = 'xelatex'  # Use xelatex for better Unicode support

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '10pt',
    'fontpkg': r'''
\usepackage{fontspec}
\defaultfontfeatures{Scale=MatchLowercase}
% Use freely available fonts that ship with TeX Live/MiKTeX
\setmainfont{Latin Modern Roman}
\setsansfont{Latin Modern Sans}
\setmonofont{Latin Modern Mono}[Scale=0.9]
''',
    'preamble': r'''
% Define Unicode characters not available in Latin Modern fonts
\usepackage{newunicodechar}
% Box-drawing - simple ASCII replacements
\newunicodechar{─}{-}
\newunicodechar{│}{|}
\newunicodechar{┌}{+}
\newunicodechar{┐}{+}
\newunicodechar{└}{+}
\newunicodechar{┘}{+}
\newunicodechar{├}{+}
\newunicodechar{┤}{+}
\newunicodechar{═}{=}
% Special symbols
\newunicodechar{✓}{[OK]}
\newunicodechar{✗}{[X]}
\newunicodechar{⚠}{[!]}
\newunicodechar{❌}{[X]}
% Variation selector (invisible)
\newunicodechar{︎}{}
''',
    'extraclassoptions': 'openany,oneside',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'NFCAccessControl.tex', 'NFC Access Control System Documentation',
     'RWU NFC Lab', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'nfcaccesscontrol', 'NFC Access Control System Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'NFCAccessControl', 'NFC Access Control System Documentation',
     author, 'NFCAccessControl', 'Professional access control system using PN532 NFC reader.',
     'Miscellaneous'),
]
